"""add tags saved filters soft delete fulltext

Revision ID: 78c67a092879
Revises: 
Create Date: 2026-04-13 10:49:33.913661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78c67a092879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_fulltext_content', 'comments', ['content'], unique=False, mysql_prefix='FULLTEXT')
    op.add_column('tickets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('tickets', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index('ix_ticket_fulltext_title_description', 'tickets', ['title', 'description'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index(op.f('ix_tickets_is_deleted'), 'tickets', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'tickets', 'users', ['deleted_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_is_deleted'), table_name='tickets')
    op.drop_index('ix_ticket_fulltext_title_description', table_name='tickets', mysql_prefix='FULLTEXT')
    op.alter_column('tickets', 'description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('tickets', 'deleted_by_user_id')
    op.drop_column('tickets', 'deleted_at')
    op.drop_column('tickets', 'is_deleted')
    op.drop_index('ix_comment_fulltext_content', table_name='comments', mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###
